[project]
name = "coding-challenge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.1"
dependencies = [
    "ruff>=0.14.8",
]

[dependency-groups]
dev = [
    "pre-commit>=4.5.0",
]
